export const products1 = `
  [
    {
      "id": 15685,
      "name": "Mountain Bike 1",
      "brand": "Trek",
      "type": "bicycles",
      "price": 2448,
      "color": "Black",
      "size": "M",
      "weight": 12.5,
      "description": "Durable mountain bike for off-road riding.",
      "arrival_date": "2024-09-01",
      "quantity": 1,
      "img": "bike.jpg"
    },
    {
      "id": 77890,
      "name": "Bicycle Pump",
      "brand": "Topeak",
      "type": "accessories",
      "price": 72,
      "color": "Silver",
      "weight": 0.4,
      "description": "Compact pump for maintaining tire pressure.",
      "arrival_date": "2024-08-15",
      "quantity": 10,
      "img": "access.jpg"
    },
    {
      "id": 58321,
      "name": "Bicycle Helmet",
      "brand": "Giro",
      "type": "accessories",
      "price": 140,
      "color": "Blue",
      "size": "M",
      "weight": 0.35,
      "description": "Lightweight and durable helmet for head protection.",
      "arrival_date": "2024-09-05",
      "quantity": 8,
      "img": "access.jpg"
    },
    {
      "id": 98765,
      "name": "Electric Bike 1",
      "brand": "Specialized",
      "type": "bicycles",
      "price": 5000,
      "color": "Green",
      "size": "M",
      "weight": 18.7,
      "description": "Electric bike for comfortable urban transportation.",
      "arrival_date": "2024-08-20",
      "quantity": 5,
      "img": "bike.jpg"
    },
    {
      "id": 11223,
      "name": "Folding Bike 1",
      "brand": "Dahon",
      "type": "bicycles",
      "price": 778,
      "color": "Silver",
      "size": "S",
      "weight": 13.5,
      "description": "Compact folding bike for convenient storage and transportation.",
      "arrival_date": "2024-09-10",
      "quantity": 12,
      "img": "bike.jpg"
    },
    {
      "id": 44556,
      "name": "Mountain Bike 2",
      "brand": "Cannondale",
      "type": "bicycles",
      "price": 2052,
      "color": "Orange",
      "size": "L",
      "weight": 11.9,
      "description": "Durable mountain bike for challenging trails.",
      "arrival_date": "2024-08-25",
      "quantity": 7,
      "img": "bike.jpg"
    },
    {
      "id": 77889,
      "name": "Road Bike 2",
      "brand": "Cervelo",
      "type": "bicycles",
      "price": 1272,
      "color": "White",
      "size": "M",
      "weight": 9.5,
      "description": "High-performance road bike for racing.",
      "arrival_date": "2024-02-15",
      "quantity": 18,
      "img": "bike.jpg"
    },
    {
      "id": 22334,
      "name": "City Bike 2",
      "brand": "Raleigh",
      "type": "bicycles",
      "price": 950,
      "color": "Yellow",
      "size": "M",
      "weight": 15.0,
      "description": "Stylish city bike for urban exploration.",
      "arrival_date": "2024-03-30",
      "quantity": 14,
      "img": "bike.jpg"
    },
    {
      "id": 55667,
      "name": "Electric Bike 2",
      "brand": "Brompton",
      "type": "bicycles",
      "price": 2888,
      "color": "Black",
      "size": "S",
      "weight": 17.8,
      "description": "Electric bike with elegant design for urban rides.",
      "arrival_date": "2024-09-20",
      "quantity": 9,
      "img": "bike.jpg"
    },
    {
      "id": 88990,
      "name": "Folding Bike 2",
      "brand": "Tern",
      "type": "bicycles",
      "price": 1644,
      "color": "Blue",
      "size": "M",
      "weight": 14.0,
      "description": "Versatile folding bike for urban and touring rides.",
      "arrival_date": "2024-09-25",
      "quantity": 11,
      "img": "bike.jpg"
    },
    {
      "id": 33445,
      "name": "Mountain Bike 3",
      "brand": "Santa Cruz",
      "type": "bicycles",
      "price": 2456,
      "color": "Green",
      "size": "L",
      "weight": 12.3,
      "description": "High-quality mountain bike for serious riders.",
      "arrival_date": "2024-06-30",
      "quantity": 13,
      "img": "bike.jpg"
    },
    {
      "id": 66778,
      "name": "Road Bike 3",
      "brand": "Pinarello",
      "type": "bicycles",
      "price": 1280,
      "color": "Red",
      "size": "M",
      "weight": 9.2,
      "description": "Top-tier road bike for professional cyclists.",
      "arrival_date": "2024-10-05",
      "quantity": 6,
      "img": "bike.jpg"
    },
    {
      "id": 99001,
      "name": "City Bike 3",
      "brand": "Kona",
      "type": "bicycles",
      "price": 1354,
      "color": "Black",
      "size": "S",
      "weight": 14.5,
      "description": "Reliable city bike for daily use.",
      "arrival_date": "2024-10-10",
      "quantity": 17,
      "img": "bike.jpg"
    },
    {
      "id": 77389,
      "name": "Bicycle Gloves",
      "brand": "Pearl Izumi",
      "type": "accessories",
      "price": 60,
      "color": "Black",
      "size": "L",
      "weight": 0.1,
      "description": "Warm and comfortable gloves for cyclists.",
      "arrival_date": "2024-09-15",
      "quantity": 18,
      "img": "access.jpg"
    },
    {
      "id": 22465,
      "name": "Bicycle Pump with Gauge",
      "brand": "Topeak",
      "type": "accessories",
      "price": 88,
      "color": "Black",
      "weight": 0.5,
      "description": "Compact pump with gauge for precise pressure control.",
      "arrival_date": "2024-08-30",
      "quantity": 14,
      "img": "access.jpg"
    },
    {
      "id": 75991,
      "name": "Bicycle Light with USB Charging",
      "brand": "Cateye",
      "type": "accessories",
      "price": 72,
      "color": "Black",
      "weight": 0.2,
      "description": "Light with USB charging capability.",
      "arrival_date": "2024-10-25",
      "quantity": 19,
      "img": "access.jpg"
    },
    {
      "id": 37896,
      "name": "Bicycle Pump with Gauge and Adapter",
      "brand": "Topeak",
      "type": "accessories",
      "price": 104,
      "color": "Silver",
      "weight": 0.6,
      "description": "Compact pump with gauge and adapter for different valve types.",
      "arrival_date": "2024-10-30",
      "quantity": 3,
      "img": "access.jpg"
    },
    {
      "id": 66779,
      "name": "City Bike 4",
      "brand": "Electra",
      "type": "bicycles",
      "price": 1196,
      "color": "Green",
      "size": "M",
      "weight": 15.2,
      "description": "Stylish and comfortable city bike.",
      "arrival_date": "2024-11-05",
      "quantity": 2,
      "img": "bike.jpg"
    },
    {
      "id": 99002,
      "name": "Electric Bike 4",
      "brand": "Gocycle",
      "type": "bicycles",
      "price": 3304,
      "color": "Yellow",
      "size": "S",
      "weight": 19.0,
      "description": "Advanced electric bike with unique design.",
      "arrival_date": "2024-11-10",
      "quantity": 1,
      "img": "bike.jpg"
    },
    {
      "id": 63868,
      "name": "Bicycle Helmet with Mirror",
      "brand": "Giro",
      "type": "accessories",
      "price": 180,
      "color": "Black",
      "size": "M",
      "weight": 0.4,
      "description": "Helmet with built-in mirror for road monitoring.",
      "arrival_date": "2024-10-05",
      "quantity": 6,
      "img": "access.jpg"
    }
  ]
`
