export const products2 = `
[
    {
      "id": 67345,
      "name": "Bicycle Light",
      "brand": "Cateye",
      "type": "accessories",
      "price": 48,
      "color": "Black",
      "weight": 0.15,
      "description": "Bright light for safe night rides.",
      "arrival_date": "2024-01-01",
      "quantity": 15,
      "img": "access.jpg"
    },
    {
      "id": 67890,
      "name": "Road Bike 1",
      "brand": "Giant",
      "type": "bicycles",
      "price": 2060,
      "color": "Red",
      "size": "L",
      "weight": 9.8,
      "description": "Lightweight road bike for long rides.",
      "arrival_date": "2024-05-15",
      "quantity": 4,
      "img": "bike.jpg"
    },
    {
      "id": 54321,
      "name": "City Bike 1",
      "brand": "Schwinn",
      "type": "bicycles",
      "price": 832,
      "color": "Blue",
      "size": "S",
      "weight": 14.2,
      "description": "Comfortable city bike for daily rides.",
      "arrival_date": "2024-01-05",
      "quantity": 0,
      "img": "bike.jpg"
    },
    {
      "id": 68765,
      "name": "Bicycle Computer",
      "brand": "Garmin",
      "type": "accessories",
      "price": 240,
      "color": "Black",
      "weight": 0.2,
      "description": "Multifunctional computer for tracking progress.",
      "arrival_date": "2024-08-20",
      "quantity": 5,
      "img": "access.jpg"
    },
    {
      "id": 11466,
      "name": "Bicycle Lock",
      "brand": "Kryptonite",
      "type": "accessories",
      "price": 100,
      "color": "Black",
      "weight": 1.2,
      "description": "Reliable lock for protecting bicycle from theft.",
      "arrival_date": "2024-09-10",
      "quantity": 12,
      "img": "access.jpg"
    },
    {
      "id": 40556,
      "name": "Bicycle Rack",
      "brand": "Topeak",
      "type": "accessories",
      "price": 120,
      "color": "Gray",
      "weight": 0.8,
      "description": "Durable rack for carrying cargo.",
      "arrival_date": "2024-08-25",
      "quantity": 7,
      "img": "access.jpg"
    },
    {
      "id": 22335,
      "name": "Electric Bike 3",
      "brand": "VanMoof",
      "type": "bicycles",
      "price": 3696,
      "color": "Silver",
      "size": "M",
      "weight": 18.5,
      "description": "Innovative electric bike with smart features.",
      "arrival_date": "2024-10-15",
      "quantity": 16,
      "img": "bike.jpg"
    },
    {
      "id": 55668,
      "name": "Folding Bike 3",
      "brand": "Brompton",
      "type": "bicycles",
      "price": 2048,
      "color": "Red",
      "size": "S",
      "weight": 13.8,
      "description": "Premium folding bike for urban mobility.",
      "arrival_date": "2024-10-20",
      "quantity": 4,
      "img": "bike.jpg"
    },
    {
      "id": 88991,
      "name": "Mountain Bike 4",
      "brand": "Yeti",
      "type": "bicycles",
      "price": 2464,
      "color": "Blue",
      "size": "L",
      "weight": 12.7,
      "description": "Bike for advanced riders with performance orientation.",
      "arrival_date": "2024-10-25",
      "quantity": 19,
      "img": "bike.jpg"
    },
    {
      "id": 33446,
      "name": "Road Bike 4",
      "brand": "Colnago",
      "type": "bicycles",
      "price": 1288,
      "color": "Black",
      "size": "M",
      "weight": 9.0,
      "description": "Classic road bike with modern technology.",
      "arrival_date": "2024-10-30",
      "quantity": 3,
      "img": "bike.jpg"
    },
    {
      "id": 55388,
      "name": "Bicycle Helmet with Ventilation",
      "brand": "Giro",
      "type": "accessories",
      "price": 160,
      "color": "White",
      "size": "L",
      "weight": 0.4,
      "description": "Helmet with ventilation system for comfort in hot weather.",
      "arrival_date": "2024-04-20",
      "quantity": 9,
      "img": "access.jpg"
    },
    {
      "id": 81110,
      "name": "Bicycle Bottle Holder",
      "brand": "Topeak",
      "type": "accessories",
      "price": 32,
      "color": "Black",
      "weight": 0.2,
      "description": "Convenient holder for bottle on handlebar.",
      "arrival_date": "2024-09-25",
      "quantity": 0,
      "img": "access.jpg"
    },
    {
      "id": 34895,
      "name": "Bicycle Pump with Adapter",
      "brand": "Topeak",
      "type": "accessories",
      "price": 80,
      "color": "Silver",
      "weight": 0.45,
      "description": "Compact pump with adapter for different valve types.",
      "arrival_date": "2024-09-30",
      "quantity": 13,
      "img": "access.jpg"
    },
    {
      "id": 63868,
      "name": "Bicycle Helmet with Mirror",
      "brand": "Giro",
      "type": "accessories",
      "price": 180,
      "color": "Black",
      "size": "M",
      "weight": 0.4,
      "description": "Helmet with built-in mirror for road monitoring.",
      "arrival_date": "2024-10-05",
      "quantity": 6,
      "img": "access.jpg"
    },
    {
      "id": 79001,
      "name": "Bicycle Light with Motion Sensor",
      "brand": "Cateye",
      "type": "accessories",
      "price": 60,
      "color": "Black",
      "weight": 0.18,
      "description": "Light with motion sensor for automatic activation.",
      "arrival_date": "2024-10-10",
      "quantity": 0,
      "img": "access.jpg"
    },
    {
      "id": 67335,
      "name": "Bicycle Pump with Car Adapter",
      "brand": "Topeak",
      "type": "accessories",
      "price": 96,
      "color": "Black",
      "weight": 0.55,
      "description": "Multifunctional pump for bicycle and car.",
      "arrival_date": "2024-10-15",
      "quantity": 16,
      "img": "access.jpg"
    },
    {
      "id": 78668,
      "name": "Bicycle Helmet with Shock Absorption System",
      "brand": "Giro",
      "type": "accessories",
      "price": 200,
      "color": "Blue",
      "size": "L",
      "weight": 0.45,
      "description": "Helmet with shock absorption system for additional protection.",
      "arrival_date": "2024-10-20",
      "quantity": 4,
      "img": "access.jpg"
    },
    {
      "id": 35579,
      "name": "Bicycle Helmet with Cooling System",
      "brand": "Giro",
      "type": "accessories",
      "price": 220,
      "color": "White",
      "size": "M",
      "weight": 0.5,
      "description": "Helmet with cooling system for comfort in hot weather.",
      "arrival_date": "2024-11-05",
      "quantity": 2,
      "img": "access.jpg"
    },
    {
      "id": 95602,
      "name": "Bicycle Light with Motion Sensor and USB Charging",
      "brand": "Cateye",
      "type": "accessories",
      "price": 80,
      "color": "Black",
      "weight": 0.22,
      "description": "Light with motion sensor and USB charging capability.",
      "arrival_date": "2024-11-10",
      "quantity": 1,
      "img": "access.jpg"
    },
    {
      "id": 22396,
      "name": "Bicycle Pump with Gauge, Adapter and USB Charging",
      "brand": "Topeak",
      "type": "accessories",
      "price": 120,
      "color": "Black",
      "weight": 0.65,
      "description": "Multifunctional pump with gauge, adapter and USB charging.",
      "arrival_date": "2024-11-15",
      "quantity": 0,
      "img": "access.jpg"
    }
  ]
`
